apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-liby
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-liby@sha256:4c25fb83b8b8dd66059ddcdf2e6a856728277adf0b5fff1a018500a3f37b502b
        name: my-nodejs
        resources: {}
status: {}
